package strings

// Code generated by sketch/scripts/bind-module-data DO NOT EDIT
//
// Sources:
// strings.skt

const SketchCode = `
; strings.skt
(defn
  join
  "Returns a new string made by concatenating the items in 'elements',
    placing 'separator' between each one."
  (elements separator)
  (if
    (empty? (rest elements)) ; I.e. strings has one item in it
    (first elements)
    (+ (first elements) separator (join (rest elements) separator))))

(export-as strings (join))
`
